/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signInUp;

/**
 *
 * @author Sem
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        forgotPass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SU = new javax.swing.JLabel();
        desc4 = new javax.swing.JLabel();
        desc5 = new javax.swing.JLabel();
        SIGNUP = new javax.swing.JLabel();
        userSignIn = new javax.swing.JTextField();
        signUpUser = new javax.swing.JLabel();
        signUpPass = new javax.swing.JLabel();
        passSignIn = new javax.swing.JPasswordField();
        SIGNIN1 = new javax.swing.JLabel();
        userSignIn1 = new javax.swing.JTextField();
        userSignIn2 = new javax.swing.JTextField();
        userSignIn3 = new javax.swing.JTextField();
        userSignIn4 = new javax.swing.JTextField();
        userSignIn5 = new javax.swing.JTextField();
        signUpUser1 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        typeUser = new javax.swing.JComboBox<>();
        cont = new javax.swing.JLabel();
        signUpUser6 = new javax.swing.JLabel();
        SU1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 540));
        setPreferredSize(new java.awt.Dimension(810, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgotPass.setBackground(new java.awt.Color(255, 255, 255));
        forgotPass.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        forgotPass.setForeground(new java.awt.Color(0, 204, 204));
        forgotPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPass.setText("Forgot Password?");
        jPanel4.add(forgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 306, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medlogo.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, 110));

        SU.setBackground(new java.awt.Color(255, 255, 255));
        SU.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        SU.setForeground(new java.awt.Color(255, 255, 255));
        SU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SU.setText("Welcome Back!");
        jPanel4.add(SU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, 40));

        desc4.setBackground(new java.awt.Color(255, 255, 255));
        desc4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        desc4.setForeground(new java.awt.Color(255, 255, 255));
        desc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc4.setText("login your personal details.");
        desc4.setAutoscrolls(true);
        desc4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(desc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 290, -1));

        desc5.setBackground(new java.awt.Color(255, 255, 255));
        desc5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        desc5.setForeground(new java.awt.Color(255, 255, 255));
        desc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc5.setText("To keep connected with us, please");
        desc5.setAutoscrolls(true);
        desc5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(desc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 290, -1));

        SIGNUP.setBackground(new java.awt.Color(255, 255, 255));
        SIGNUP.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        SIGNUP.setForeground(new java.awt.Color(0, 204, 204));
        SIGNUP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SIGNUP.setText("SIGN IN");
        SIGNUP.setDoubleBuffered(true);
        SIGNUP.setOpaque(true);
        jPanel4.add(SIGNUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 490));

        userSignIn.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        userSignIn.setForeground(new java.awt.Color(204, 204, 255));
        userSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignInActionPerformed(evt);
            }
        });
        jPanel1.add(userSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 220, 30));

        signUpUser.setBackground(new java.awt.Color(255, 255, 255));
        signUpUser.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        signUpUser.setForeground(new java.awt.Color(0, 204, 204));
        signUpUser.setText("Type");
        jPanel1.add(signUpUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, 30));

        signUpPass.setBackground(new java.awt.Color(255, 255, 255));
        signUpPass.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        signUpPass.setForeground(new java.awt.Color(0, 204, 204));
        signUpPass.setText("Password");
        jPanel1.add(signUpPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 70, 30));

        passSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSignInActionPerformed(evt);
            }
        });
        jPanel1.add(passSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 220, 30));

        SIGNIN1.setBackground(new java.awt.Color(0, 204, 204));
        SIGNIN1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        SIGNIN1.setForeground(new java.awt.Color(255, 255, 255));
        SIGNIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SIGNIN1.setText("SIGN UP");
        SIGNIN1.setDoubleBuffered(true);
        SIGNIN1.setOpaque(true);
        jPanel1.add(SIGNIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 130, 30));

        userSignIn1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        userSignIn1.setForeground(new java.awt.Color(204, 204, 255));
        userSignIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignIn1ActionPerformed(evt);
            }
        });
        jPanel1.add(userSignIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 220, 30));

        userSignIn2.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        userSignIn2.setForeground(new java.awt.Color(204, 204, 255));
        userSignIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignIn2ActionPerformed(evt);
            }
        });
        jPanel1.add(userSignIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 220, 30));

        userSignIn3.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        userSignIn3.setForeground(new java.awt.Color(204, 204, 255));
        userSignIn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignIn3ActionPerformed(evt);
            }
        });
        jPanel1.add(userSignIn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 220, 30));

        userSignIn4.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        userSignIn4.setForeground(new java.awt.Color(204, 204, 255));
        userSignIn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignIn4ActionPerformed(evt);
            }
        });
        jPanel1.add(userSignIn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 220, 30));

        userSignIn5.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        userSignIn5.setForeground(new java.awt.Color(204, 204, 255));
        userSignIn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignIn5ActionPerformed(evt);
            }
        });
        jPanel1.add(userSignIn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 220, 30));

        signUpUser1.setBackground(new java.awt.Color(255, 255, 255));
        signUpUser1.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        signUpUser1.setForeground(new java.awt.Color(0, 204, 204));
        signUpUser1.setText("Email");
        jPanel1.add(signUpUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 30));

        fname.setBackground(new java.awt.Color(255, 255, 255));
        fname.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 204, 204));
        fname.setText("First Name");
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 30));

        mname.setBackground(new java.awt.Color(255, 255, 255));
        mname.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        mname.setForeground(new java.awt.Color(0, 204, 204));
        mname.setText("Middle Name");
        jPanel1.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 30));

        lname.setBackground(new java.awt.Color(255, 255, 255));
        lname.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 204, 204));
        lname.setText("Last Name");
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 30));

        typeUser.setEditable(true);
        typeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Patient", "Doctor", "Staff" }));
        typeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeUserActionPerformed(evt);
            }
        });
        jPanel1.add(typeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 220, 30));

        cont.setBackground(new java.awt.Color(255, 255, 255));
        cont.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        cont.setForeground(new java.awt.Color(0, 204, 204));
        cont.setText("Contact Number");
        jPanel1.add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 30));

        signUpUser6.setBackground(new java.awt.Color(255, 255, 255));
        signUpUser6.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        signUpUser6.setForeground(new java.awt.Color(0, 204, 204));
        signUpUser6.setText("Date of Birth");
        jPanel1.add(signUpUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, 30));

        SU1.setBackground(new java.awt.Color(0, 204, 204));
        SU1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        SU1.setForeground(new java.awt.Color(0, 204, 204));
        SU1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SU1.setText("SIGN UP");
        jPanel1.add(SU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 174, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSignInActionPerformed

    private void passSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passSignInActionPerformed

    private void userSignIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSignIn1ActionPerformed

    private void userSignIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignIn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSignIn2ActionPerformed

    private void userSignIn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignIn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSignIn3ActionPerformed

    private void userSignIn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignIn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSignIn4ActionPerformed

    private void userSignIn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignIn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSignIn5ActionPerformed

    private void typeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SIGNIN1;
    private javax.swing.JLabel SIGNUP;
    private javax.swing.JLabel SU;
    private javax.swing.JLabel SU1;
    private javax.swing.JLabel cont;
    private javax.swing.JLabel desc4;
    private javax.swing.JLabel desc5;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel forgotPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel mname;
    private javax.swing.JPasswordField passSignIn;
    private javax.swing.JLabel signUpPass;
    private javax.swing.JLabel signUpUser;
    private javax.swing.JLabel signUpUser1;
    private javax.swing.JLabel signUpUser6;
    private javax.swing.JComboBox<String> typeUser;
    private javax.swing.JTextField userSignIn;
    private javax.swing.JTextField userSignIn1;
    private javax.swing.JTextField userSignIn2;
    private javax.swing.JTextField userSignIn3;
    private javax.swing.JTextField userSignIn4;
    private javax.swing.JTextField userSignIn5;
    // End of variables declaration//GEN-END:variables
}
