/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signInUp;

/**
 *
 * @author Sem
 */
public class signIn extends javax.swing.JFrame {

    /**
     * Creates new form signIn
     */
    public signIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holder = new javax.swing.JPanel();
        loginbg = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        SI = new javax.swing.JLabel();
        signInUser = new javax.swing.JLabel();
        userSignIn = new javax.swing.JTextField();
        signInPass = new javax.swing.JLabel();
        passSignIn = new javax.swing.JPasswordField();
        forgotPass = new javax.swing.JLabel();
        SIGNIN1 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        desc1 = new javax.swing.JLabel();
        desc2 = new javax.swing.JLabel();
        desc3 = new javax.swing.JLabel();
        desc4 = new javax.swing.JLabel();
        desc5 = new javax.swing.JLabel();
        SIGNUP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        holder.setBackground(new java.awt.Color(255, 255, 255));
        holder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginbg.setBackground(new java.awt.Color(0, 204, 204));
        loginbg.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        loginbg.setName("dashboard"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SI.setBackground(new java.awt.Color(0, 204, 204));
        SI.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        SI.setForeground(new java.awt.Color(0, 204, 204));
        SI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SI.setText("SIGN IN");
        jPanel4.add(SI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 174, 53));

        signInUser.setBackground(new java.awt.Color(255, 255, 255));
        signInUser.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        signInUser.setForeground(new java.awt.Color(0, 204, 204));
        signInUser.setText("Email");
        jPanel4.add(signInUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        userSignIn.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        userSignIn.setForeground(new java.awt.Color(204, 204, 255));
        userSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignInActionPerformed(evt);
            }
        });
        jPanel4.add(userSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, 30));

        signInPass.setBackground(new java.awt.Color(255, 255, 255));
        signInPass.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        signInPass.setForeground(new java.awt.Color(0, 204, 204));
        signInPass.setText("Password");
        jPanel4.add(signInPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        passSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSignInActionPerformed(evt);
            }
        });
        jPanel4.add(passSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 220, 30));

        forgotPass.setBackground(new java.awt.Color(255, 255, 255));
        forgotPass.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        forgotPass.setForeground(new java.awt.Color(0, 204, 204));
        forgotPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPass.setText("Forgot Password?");
        jPanel4.add(forgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 150, -1));

        SIGNIN1.setBackground(new java.awt.Color(0, 204, 204));
        SIGNIN1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        SIGNIN1.setForeground(new java.awt.Color(255, 255, 255));
        SIGNIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SIGNIN1.setText("SIGN IN");
        SIGNIN1.setDoubleBuffered(true);
        SIGNIN1.setOpaque(true);
        jPanel4.add(SIGNIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 130, 30));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medlogo.png"))); // NOI18N

        desc1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        desc1.setForeground(new java.awt.Color(255, 255, 255));
        desc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc1.setText("Your health,");

        desc2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        desc2.setForeground(new java.awt.Color(255, 255, 255));
        desc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc2.setText("our priority.");

        desc3.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        desc3.setForeground(new java.awt.Color(255, 255, 255));
        desc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc3.setText("Sign Up now!");

        desc4.setBackground(new java.awt.Color(255, 255, 255));
        desc4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        desc4.setForeground(new java.awt.Color(255, 255, 255));
        desc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc4.setText("Provide your details to book an appointment");
        desc4.setAutoscrolls(true);
        desc4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        desc5.setBackground(new java.awt.Color(255, 255, 255));
        desc5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        desc5.setForeground(new java.awt.Color(255, 255, 255));
        desc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc5.setText("and receive quality care.");
        desc5.setAutoscrolls(true);
        desc5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SIGNUP.setBackground(new java.awt.Color(255, 255, 255));
        SIGNUP.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        SIGNUP.setForeground(new java.awt.Color(0, 204, 204));
        SIGNUP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SIGNUP.setText("SIGN UP");
        SIGNUP.setDoubleBuffered(true);
        SIGNUP.setOpaque(true);

        javax.swing.GroupLayout loginbgLayout = new javax.swing.GroupLayout(loginbg);
        loginbg.setLayout(loginbgLayout);
        loginbgLayout.setHorizontalGroup(
            loginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginbgLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(loginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginbgLayout.createSequentialGroup()
                            .addComponent(LOGO)
                            .addGap(176, 176, 176))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginbgLayout.createSequentialGroup()
                            .addGroup(loginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(desc5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(desc4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(83, 83, 83))
                        .addGroup(loginbgLayout.createSequentialGroup()
                            .addComponent(desc1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(desc2)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginbgLayout.createSequentialGroup()
                        .addComponent(desc3)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginbgLayout.createSequentialGroup()
                        .addComponent(SIGNUP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );
        loginbgLayout.setVerticalGroup(
            loginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginbgLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desc1)
                    .addComponent(desc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desc3)
                .addGap(18, 18, 18)
                .addComponent(desc4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desc5)
                .addGap(31, 31, 31)
                .addComponent(SIGNUP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        holder.add(loginbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        getContentPane().add(holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSignInActionPerformed

    private void passSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel SI;
    private javax.swing.JLabel SIGNIN1;
    private javax.swing.JLabel SIGNUP;
    private javax.swing.JLabel desc1;
    private javax.swing.JLabel desc2;
    private javax.swing.JLabel desc3;
    private javax.swing.JLabel desc4;
    private javax.swing.JLabel desc5;
    private javax.swing.JLabel forgotPass;
    private javax.swing.JPanel holder;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel loginbg;
    private javax.swing.JPasswordField passSignIn;
    private javax.swing.JLabel signInPass;
    private javax.swing.JLabel signInUser;
    private javax.swing.JTextField userSignIn;
    // End of variables declaration//GEN-END:variables
}
